spring.application.name=telegram

spring.datasource.url=jdbc:postgresql://pg-1cb1052e-shradheyrastogi91-3b4d.i.aivencloud.com:19597/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_HsiaCqygVGXNmZ9s7UQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:promtvault-super-secret-jwt-key-must-be-at-least-64-characters-long-for-hs512}
app.jwt.access-expiration-ms=604800000
<<<<<<< HEAD

b2.key-id=005fefce6c53a400000000001
b2.application-key=K005fwZ5ifMquNNaw77UDY8R2kdKxxM
b2.bucket-name=stories-telegram
b2.bucket-id=dffe4facce06ece593ea0410

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
=======
>>>>>>> main
