spring.application.name=telegram

spring.datasource.url=jdbc:postgresql://pg-1cb1052e-shradheyrastogi91-3b4d.i.aivencloud.com:19597/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_HsiaCqygVGXNmZ9s7UQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:promtvault-super-secret-jwt-key-must-be-at-least-64-characters-long-for-hs512}
app.jwt.access-expiration-ms=604800000
